### PR TITLE
Qr code integration

### PR DESCRIPTION
**Pull request by fraggerfox**
Hello

I added a basic QR Code Integration into your existing label system and thought I could shared the changes with you.

Note: The currency symbol has changed from Euro.

### CODE REVIEW

**Comment by keikoro** [comment]
IIRC the QR code was removed from Metalab's labels because it was never used anyway. Not saying it's not a cool integration to have _if_ one wants it, just adding this as a note (maybe the changes could go into another branch).

Now I'm wondering what you're going to use it for!

**Comment by TomK32** [comment]
How do you know ether the QR code is being used? Adding some referral info to the QR code url could help here.

**Comment by fraggerfox** [comment]
> IIRC the QR code was removed from Metalab's labels because it was never used anyway. Not saying it's not a cool integration to have if one wants it, just adding this as a note (maybe the changes could go into another branch).

Feel free to implement it as you see fit, I am just contributing the changes I made.

> Now I'm wondering what you're going to use it for!
> 
> How do you know ether the QR code is being used? Adding some referral info to the QR code url could help here.

For the "Personal" Labels, the QR code will contain information link that you provide, otherwise it is pretty useless, the use case that I have here is to point various equipments we have in our hackspace to point to appropriate URLs so that people can get information out of it.

For "FreeStyle" Lables, QR Code is the text you give.

I should have documented the feature a bit more, I guess I was in a bit of hurry to get it working.

**Comment by keikoro** [comment]
Ahh. A link to more info totally makes sense!

The QR codes that Metalab used for its old labels contained basically all the info that was printed on the labels in plaintext, so the codes were pretty useless/redundant. :P

**Comment by fraggerfox** [comment]
labelz_with_qrcode

Yup, here is an example use case of an actual item that we have.

**Comment by jaeh** [comment]
thanks for the pull request :)

I will test this with our printer next time i am in the metalab, 
which probably means sometime today or tomorrow,
if i do not merge till tomorrow evening feel free to poke me via a message in this pull request to get a new estimate :)

**Pull request merged**
